/** "Market crash — hold or sell?" — authored scenario content for /learn/scenarios/market-crash. */
export const crash = {
  title: "Market crash — hold or sell?",
  steps: [
    { day: 1, breaking: "BREAKING · DAY 1", spx: "S&P −7%", copy: "Markets open sharply lower on virus headlines. Your practice portfolio is down $620.", simbot: "Big red day. Before anything else — did the business you own change today, or just the price?", choices: [{ label: "😱 Sell everything — stop the bleeding", tone: "bad" }, { label: "🧘 Hold — my thesis hasn't changed", sub: "time in the market beats timing the market", tone: "good" }, { label: "🛒 Buy more at a discount", tone: "ok" }] },
    { day: 3, breaking: "BREAKING · DAY 3", spx: "S&P −18%", copy: "Markets plunge for a third day. Your practice portfolio is down $1,840.", simbot: "Your phone is buzzing. Everyone's selling. Your VOO position is solid long-term — what do you do?", choices: [{ label: "😱 Sell everything — stop the bleeding", tone: "bad" }, { label: "🧘 Hold — my thesis hasn't changed", sub: "time in the market beats timing the market", tone: "good" }, { label: "🛒 Buy more at a discount", tone: "ok" }] },
    { day: 4, breaking: "BREAKING · DAY 4", spx: "S&P −12%", copy: "The worst single day since 1987. Circuit breakers halt trading twice.", simbot: "This is the moment most people quit. Nothing about VOO's 500 companies changed overnight. Your call?", choices: [{ label: "😱 Sell now, it's only getting worse", tone: "bad" }, { label: "🧘 Hold and stop checking", sub: "volatility isn't loss until you sell", tone: "good" }, { label: "🛒 Add a little more", tone: "ok" }] },
    { day: 12, breaking: "DAY 12", spx: "S&P −34% from peak", copy: "The bottom — though nobody knows it yet. Headlines say 'a lost decade ahead'.", simbot: "If you held, you're down ~34%. If you sold on day 3, you're down 18% in cash. What now?", choices: [{ label: "Stay in cash until it's 'safe'", tone: "bad" }, { label: "🧘 Keep holding", sub: "the plan is the plan", tone: "good" }, { label: "🛒 Buy — this is the discount", tone: "ok" }] },
    { day: 60, breaking: "DAY 60", spx: "S&P +30% off the low", copy: "A furious rally. Sellers who waited for 'safe' missed the biggest up-days in history.", simbot: "The best 10 days of 2020 all came inside the crash. Missing them halved the year's return.", choices: [{ label: "Continue → what happened next", tone: "good" }] },
    { day: 365, breaking: "ONE YEAR LATER", spx: "S&P +75% from the low", copy: "A year on, the index is at new highs. Holders recovered everything and more; sellers are still waiting.", simbot: "Lesson: the question in a crash is 'did the business change?' — not 'how do I feel?'", choices: [{ label: "Finish · +25 XP", tone: "good" }] },
  ],
};